version: "3.7"

services:
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - .:/src
    # command: ls /src -a 
    command: generate -i ./src/openapi.json -g typescript-axios -o /src/src/api-client --skip-validate-spec
