/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * An enumeration.
 * @export
 * @enum {string}
 */

export const AttackBallType = {
    High: 'high',
    Medium: 'medium',
    Quick: 'quick',
    Other: 'other'
} as const;

export type AttackBallType = typeof AttackBallType[keyof typeof AttackBallType];


/**
 * 
 * @export
 * @interface AttackBase
 */
export interface AttackBase {
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'home_team_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'away_team_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'home_team_set_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'away_team_set_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'attack_start_zone': number;
    /**
     * 
     * @type {number}
     * @memberof AttackBase
     */
    'attack_end_zone': number;
    /**
     * 
     * @type {AttackBallType}
     * @memberof AttackBase
     */
    'attack_ball_type': AttackBallType;
    /**
     * 
     * @type {AttackSkill}
     * @memberof AttackBase
     */
    'attack_skill': AttackSkill;
    /**
     * 
     * @type {AttackEvaluationType}
     * @memberof AttackBase
     */
    'attack_evaluation': AttackEvaluationType;
    /**
     * 
     * @type {string}
     * @memberof AttackBase
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackBase
     */
    'match_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackBase
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackBase
     */
    'player_id': string;
}


/**
 * An enumeration.
 * @export
 * @enum {string}
 */

export const AttackEvaluationType = {
    Kill: 'kill',
    OverPass: 'overPass',
    PossibleCover: 'possibleCover',
    Blocked: 'blocked',
    InPlay: 'inPlay',
    Error: 'error'
} as const;

export type AttackEvaluationType = typeof AttackEvaluationType[keyof typeof AttackEvaluationType];


/**
 * 
 * @export
 * @interface AttackResponse
 */
export interface AttackResponse {
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'home_team_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'away_team_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'home_team_set_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'away_team_set_score': number;
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'attack_start_zone': number;
    /**
     * 
     * @type {number}
     * @memberof AttackResponse
     */
    'attack_end_zone': number;
    /**
     * 
     * @type {AttackBallType}
     * @memberof AttackResponse
     */
    'attack_ball_type': AttackBallType;
    /**
     * 
     * @type {AttackSkill}
     * @memberof AttackResponse
     */
    'attack_skill': AttackSkill;
    /**
     * 
     * @type {AttackEvaluationType}
     * @memberof AttackResponse
     */
    'attack_evaluation': AttackEvaluationType;
    /**
     * 
     * @type {string}
     * @memberof AttackResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackResponse
     */
    'match_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackResponse
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackResponse
     */
    'player_id': string;
    /**
     * 
     * @type {string}
     * @memberof AttackResponse
     */
    'uuid': string;
}


/**
 * An enumeration.
 * @export
 * @enum {string}
 */

export const AttackSkill = {
    HeadSpike: 'headSpike',
    SoftSpike: 'softSpike',
    Dink: 'dink'
} as const;

export type AttackSkill = typeof AttackSkill[keyof typeof AttackSkill];


/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface Match
 */
export interface Match {
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    'home_team_id': string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    'away_team_id': string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    'season_id': string;
    /**
     * 
     * @type {string}
     * @memberof Match
     */
    'youtube_url': string;
}
/**
 * 
 * @export
 * @interface MatchPostRequest
 */
export interface MatchPostRequest {
    /**
     * 
     * @type {Match}
     * @memberof MatchPostRequest
     */
    'Match': Match;
    /**
     * 
     * @type {{ [key: string]: PlayerMatchInfo; }}
     * @memberof MatchPostRequest
     */
    'PlayerMatchInfo': { [key: string]: PlayerMatchInfo; };
}
/**
 * 
 * @export
 * @interface MatchResponse
 */
export interface MatchResponse {
    /**
     * 
     * @type {string}
     * @memberof MatchResponse
     */
    'uuid': string;
    /**
     * 
     * @type {TeamRequest}
     * @memberof MatchResponse
     */
    'home_team': TeamRequest;
    /**
     * 
     * @type {TeamRequest}
     * @memberof MatchResponse
     */
    'away_team': TeamRequest;
    /**
     * 
     * @type {string}
     * @memberof MatchResponse
     */
    'season_name': string;
    /**
     * 
     * @type {string}
     * @memberof MatchResponse
     */
    'youtube_url': string;
}
/**
 * 
 * @export
 * @interface PlayerBase
 */
export interface PlayerBase {
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerBase
     */
    'player_number': number;
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'postion': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerBase
     */
    'weight': number;
    /**
     * 
     * @type {number}
     * @memberof PlayerBase
     */
    'height': number;
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerBase
     */
    'season_id': string;
}
/**
 * 
 * @export
 * @interface PlayerInfo
 */
export interface PlayerInfo {
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerInfo
     */
    'player_number': number;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    'postion': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerInfo
     */
    'weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerInfo
     */
    'height'?: number;
}
/**
 * 
 * @export
 * @interface PlayerMatchInfo
 */
export interface PlayerMatchInfo {
    /**
     * 
     * @type {string}
     * @memberof PlayerMatchInfo
     */
    'player_id': string;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerMatchInfo
     */
    'on_court': boolean;
    /**
     * 
     * @type {string}
     * @memberof PlayerMatchInfo
     */
    'zone_code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerMatchInfo
     */
    'libero'?: boolean;
}
/**
 * 
 * @export
 * @interface PlayerResponse
 */
export interface PlayerResponse {
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerResponse
     */
    'player_number': number;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'postion': string;
    /**
     * 
     * @type {number}
     * @memberof PlayerResponse
     */
    'weight': number;
    /**
     * 
     * @type {number}
     * @memberof PlayerResponse
     */
    'height': number;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'season_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlayerResponse
     */
    'uuid': string;
}
/**
 * 
 * @export
 * @interface SeasonBase
 */
export interface SeasonBase {
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'start_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'end_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'season_name': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'game_format': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBase
     */
    'user_id': string;
}
/**
 * 
 * @export
 * @interface SeasonCreate
 */
export interface SeasonCreate {
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'start_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'end_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'season_name': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'game_format': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonCreate
     */
    'uuid': string;
}
/**
 * 
 * @export
 * @interface SeasonResponse
 */
export interface SeasonResponse {
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'start_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'end_day': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'season_name': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'game_format': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof SeasonResponse
     */
    'uuid': string;
}
/**
 * 
 * @export
 * @interface TeamBase
 */
export interface TeamBase {
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'director': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'coach': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'trainer': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'doctor': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'season_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamBase
     */
    'user_id': string;
}
/**
 * 
 * @export
 * @interface TeamPlayers
 */
export interface TeamPlayers {
    /**
     * 
     * @type {PlayerInfo}
     * @memberof TeamPlayers
     */
    'PlayerInfo': PlayerInfo;
    /**
     * 
     * @type {boolean}
     * @memberof TeamPlayers
     */
    'onCourt': boolean;
    /**
     * 
     * @type {string}
     * @memberof TeamPlayers
     */
    'zone_code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamPlayers
     */
    'libero'?: boolean;
}
/**
 * 
 * @export
 * @interface TeamRequest
 */
export interface TeamRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamRequest
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof TeamRequest
     */
    'team_name': string;
    /**
     * 
     * @type {{ [key: string]: TeamPlayers; }}
     * @memberof TeamRequest
     */
    'players': { [key: string]: TeamPlayers; };
    /**
     * 
     * @type {string}
     * @memberof TeamRequest
     */
    'setter_postion': string;
}
/**
 * 
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'director': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'coach': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'trainer': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'doctor': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'season_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    'uuid': string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationError
     */
    'loc': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}

/**
 * AttacksApi - axios parameter creator
 * @export
 */
export const AttacksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Attack
         * @param {AttackBase} attackBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAttackAttacksPost: async (attackBase: AttackBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'attackBase' is not null or undefined
            assertParamExists('createAttackAttacksPost', 'attackBase', attackBase)
            const localVarPath = `/attacks/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(attackBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Attack
         * @param {string} attackId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAttackAttacksAttackIdDelete: async (attackId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'attackId' is not null or undefined
            assertParamExists('deleteAttackAttacksAttackIdDelete', 'attackId', attackId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteAttackAttacksAttackIdDelete', 'userId', userId)
            const localVarPath = `/attacks/{attack_id}`
                .replace(`{${"attack_id"}}`, encodeURIComponent(String(attackId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Attacks
         * @param {string} userId 
         * @param {string} matchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttacksAttacksGet: async (userId: string, matchId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getAttacksAttacksGet', 'userId', userId)
            // verify required parameter 'matchId' is not null or undefined
            assertParamExists('getAttacksAttacksGet', 'matchId', matchId)
            const localVarPath = `/attacks/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (matchId !== undefined) {
                localVarQueryParameter['match_id'] = matchId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttacksApi - functional programming interface
 * @export
 */
export const AttacksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttacksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Attack
         * @param {AttackBase} attackBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAttackAttacksPost(attackBase: AttackBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttackResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAttackAttacksPost(attackBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AttacksApi.createAttackAttacksPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Attack
         * @param {string} attackId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAttackAttacksAttackIdDelete(attackId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttackResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAttackAttacksAttackIdDelete(attackId, userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AttacksApi.deleteAttackAttacksAttackIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Attacks
         * @param {string} userId 
         * @param {string} matchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttacksAttacksGet(userId: string, matchId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttackResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttacksAttacksGet(userId, matchId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AttacksApi.getAttacksAttacksGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AttacksApi - factory interface
 * @export
 */
export const AttacksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttacksApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Attack
         * @param {AttackBase} attackBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAttackAttacksPost(attackBase: AttackBase, options?: any): AxiosPromise<AttackResponse> {
            return localVarFp.createAttackAttacksPost(attackBase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Attack
         * @param {string} attackId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAttackAttacksAttackIdDelete(attackId: string, userId: string, options?: any): AxiosPromise<AttackResponse> {
            return localVarFp.deleteAttackAttacksAttackIdDelete(attackId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Attacks
         * @param {string} userId 
         * @param {string} matchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttacksAttacksGet(userId: string, matchId: string, options?: any): AxiosPromise<Array<AttackResponse>> {
            return localVarFp.getAttacksAttacksGet(userId, matchId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AttacksApi - object-oriented interface
 * @export
 * @class AttacksApi
 * @extends {BaseAPI}
 */
export class AttacksApi extends BaseAPI {
    /**
     * 
     * @summary Create Attack
     * @param {AttackBase} attackBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttacksApi
     */
    public createAttackAttacksPost(attackBase: AttackBase, options?: RawAxiosRequestConfig) {
        return AttacksApiFp(this.configuration).createAttackAttacksPost(attackBase, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Attack
     * @param {string} attackId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttacksApi
     */
    public deleteAttackAttacksAttackIdDelete(attackId: string, userId: string, options?: RawAxiosRequestConfig) {
        return AttacksApiFp(this.configuration).deleteAttackAttacksAttackIdDelete(attackId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Attacks
     * @param {string} userId 
     * @param {string} matchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttacksApi
     */
    public getAttacksAttacksGet(userId: string, matchId: string, options?: RawAxiosRequestConfig) {
        return AttacksApiFp(this.configuration).getAttacksAttacksGet(userId, matchId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MatchesApi - axios parameter creator
 * @export
 */
export const MatchesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Match
         * @param {MatchPostRequest} matchPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMatchMatchesPost: async (matchPostRequest: MatchPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'matchPostRequest' is not null or undefined
            assertParamExists('createMatchMatchesPost', 'matchPostRequest', matchPostRequest)
            const localVarPath = `/matches/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(matchPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Match
         * @param {string} matchId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchMatchesMatchIdGet: async (matchId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'matchId' is not null or undefined
            assertParamExists('getMatchMatchesMatchIdGet', 'matchId', matchId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMatchMatchesMatchIdGet', 'userId', userId)
            const localVarPath = `/matches/{match_id}`
                .replace(`{${"match_id"}}`, encodeURIComponent(String(matchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Matches
         * @param {string} userId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchesMatchesGet: async (userId: string, skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMatchesMatchesGet', 'userId', userId)
            const localVarPath = `/matches/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MatchesApi - functional programming interface
 * @export
 */
export const MatchesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MatchesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Match
         * @param {MatchPostRequest} matchPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMatchMatchesPost(matchPostRequest: MatchPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MatchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMatchMatchesPost(matchPostRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MatchesApi.createMatchMatchesPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Match
         * @param {string} matchId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMatchMatchesMatchIdGet(matchId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MatchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMatchMatchesMatchIdGet(matchId, userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MatchesApi.getMatchMatchesMatchIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Matches
         * @param {string} userId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMatchesMatchesGet(userId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MatchResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMatchesMatchesGet(userId, skip, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['MatchesApi.getMatchesMatchesGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * MatchesApi - factory interface
 * @export
 */
export const MatchesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MatchesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Match
         * @param {MatchPostRequest} matchPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMatchMatchesPost(matchPostRequest: MatchPostRequest, options?: any): AxiosPromise<MatchResponse> {
            return localVarFp.createMatchMatchesPost(matchPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Match
         * @param {string} matchId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchMatchesMatchIdGet(matchId: string, userId: string, options?: any): AxiosPromise<MatchResponse> {
            return localVarFp.getMatchMatchesMatchIdGet(matchId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Matches
         * @param {string} userId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchesMatchesGet(userId: string, skip?: number, limit?: number, options?: any): AxiosPromise<Array<MatchResponse>> {
            return localVarFp.getMatchesMatchesGet(userId, skip, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MatchesApi - object-oriented interface
 * @export
 * @class MatchesApi
 * @extends {BaseAPI}
 */
export class MatchesApi extends BaseAPI {
    /**
     * 
     * @summary Create Match
     * @param {MatchPostRequest} matchPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApi
     */
    public createMatchMatchesPost(matchPostRequest: MatchPostRequest, options?: RawAxiosRequestConfig) {
        return MatchesApiFp(this.configuration).createMatchMatchesPost(matchPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Match
     * @param {string} matchId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApi
     */
    public getMatchMatchesMatchIdGet(matchId: string, userId: string, options?: RawAxiosRequestConfig) {
        return MatchesApiFp(this.configuration).getMatchMatchesMatchIdGet(matchId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Matches
     * @param {string} userId 
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MatchesApi
     */
    public getMatchesMatchesGet(userId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return MatchesApiFp(this.configuration).getMatchesMatchesGet(userId, skip, limit, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PlayersApi - axios parameter creator
 * @export
 */
export const PlayersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Player
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlayerPlayersPost: async (playerBase: PlayerBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playerBase' is not null or undefined
            assertParamExists('createPlayerPlayersPost', 'playerBase', playerBase)
            const localVarPath = `/players/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(playerBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePlayerPlayersDelete: async (userId: string, playerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deletePlayerPlayersDelete', 'userId', userId)
            // verify required parameter 'playerId' is not null or undefined
            assertParamExists('deletePlayerPlayersDelete', 'playerId', playerId)
            const localVarPath = `/players/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (playerId !== undefined) {
                localVarQueryParameter['player_id'] = playerId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Players
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlayersPlayersGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getPlayersPlayersGet', 'userId', userId)
            const localVarPath = `/players/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlayerPlayersPut: async (userId: string, playerId: string, playerBase: PlayerBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updatePlayerPlayersPut', 'userId', userId)
            // verify required parameter 'playerId' is not null or undefined
            assertParamExists('updatePlayerPlayersPut', 'playerId', playerId)
            // verify required parameter 'playerBase' is not null or undefined
            assertParamExists('updatePlayerPlayersPut', 'playerBase', playerBase)
            const localVarPath = `/players/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (playerId !== undefined) {
                localVarQueryParameter['player_id'] = playerId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(playerBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlayersApi - functional programming interface
 * @export
 */
export const PlayersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlayersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Player
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPlayerPlayersPost(playerBase: PlayerBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlayerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPlayerPlayersPost(playerBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PlayersApi.createPlayerPlayersPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePlayerPlayersDelete(userId: string, playerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlayerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePlayerPlayersDelete(userId, playerId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PlayersApi.deletePlayerPlayersDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Players
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPlayersPlayersGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PlayerResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPlayersPlayersGet(userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PlayersApi.getPlayersPlayersGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePlayerPlayersPut(userId: string, playerId: string, playerBase: PlayerBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlayerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePlayerPlayersPut(userId, playerId, playerBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PlayersApi.updatePlayerPlayersPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PlayersApi - factory interface
 * @export
 */
export const PlayersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlayersApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Player
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlayerPlayersPost(playerBase: PlayerBase, options?: any): AxiosPromise<PlayerResponse> {
            return localVarFp.createPlayerPlayersPost(playerBase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePlayerPlayersDelete(userId: string, playerId: string, options?: any): AxiosPromise<PlayerResponse> {
            return localVarFp.deletePlayerPlayersDelete(userId, playerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Players
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlayersPlayersGet(userId: string, options?: any): AxiosPromise<Array<PlayerResponse>> {
            return localVarFp.getPlayersPlayersGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Player
         * @param {string} userId 
         * @param {string} playerId 
         * @param {PlayerBase} playerBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlayerPlayersPut(userId: string, playerId: string, playerBase: PlayerBase, options?: any): AxiosPromise<PlayerResponse> {
            return localVarFp.updatePlayerPlayersPut(userId, playerId, playerBase, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlayersApi - object-oriented interface
 * @export
 * @class PlayersApi
 * @extends {BaseAPI}
 */
export class PlayersApi extends BaseAPI {
    /**
     * 
     * @summary Create Player
     * @param {PlayerBase} playerBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public createPlayerPlayersPost(playerBase: PlayerBase, options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).createPlayerPlayersPost(playerBase, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Player
     * @param {string} userId 
     * @param {string} playerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public deletePlayerPlayersDelete(userId: string, playerId: string, options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).deletePlayerPlayersDelete(userId, playerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Players
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public getPlayersPlayersGet(userId: string, options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).getPlayersPlayersGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Player
     * @param {string} userId 
     * @param {string} playerId 
     * @param {PlayerBase} playerBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public updatePlayerPlayersPut(userId: string, playerId: string, playerBase: PlayerBase, options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).updatePlayerPlayersPut(userId, playerId, playerBase, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SeasonsApi - axios parameter creator
 * @export
 */
export const SeasonsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Season
         * @param {SeasonBase} seasonBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSeasonSeasonsPost: async (seasonBase: SeasonBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seasonBase' is not null or undefined
            assertParamExists('createSeasonSeasonsPost', 'seasonBase', seasonBase)
            const localVarPath = `/seasons/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(seasonBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSeasonSeasonsSeasonIdDelete: async (seasonId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seasonId' is not null or undefined
            assertParamExists('deleteSeasonSeasonsSeasonIdDelete', 'seasonId', seasonId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteSeasonSeasonsSeasonIdDelete', 'userId', userId)
            const localVarPath = `/seasons/{season_id}`
                .replace(`{${"season_id"}}`, encodeURIComponent(String(seasonId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Seasons
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeasonsSeasonsGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getSeasonsSeasonsGet', 'userId', userId)
            const localVarPath = `/seasons/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {SeasonCreate} seasonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSeasonSeasonsSeasonIdPut: async (seasonId: string, userId: string, seasonCreate: SeasonCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seasonId' is not null or undefined
            assertParamExists('updateSeasonSeasonsSeasonIdPut', 'seasonId', seasonId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateSeasonSeasonsSeasonIdPut', 'userId', userId)
            // verify required parameter 'seasonCreate' is not null or undefined
            assertParamExists('updateSeasonSeasonsSeasonIdPut', 'seasonCreate', seasonCreate)
            const localVarPath = `/seasons/{season_id}`
                .replace(`{${"season_id"}}`, encodeURIComponent(String(seasonId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(seasonCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SeasonsApi - functional programming interface
 * @export
 */
export const SeasonsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SeasonsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Season
         * @param {SeasonBase} seasonBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSeasonSeasonsPost(seasonBase: SeasonBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeasonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSeasonSeasonsPost(seasonBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SeasonsApi.createSeasonSeasonsPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSeasonSeasonsSeasonIdDelete(seasonId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeasonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSeasonSeasonsSeasonIdDelete(seasonId, userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SeasonsApi.deleteSeasonSeasonsSeasonIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Seasons
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSeasonsSeasonsGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SeasonResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSeasonsSeasonsGet(userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SeasonsApi.getSeasonsSeasonsGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {SeasonCreate} seasonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSeasonSeasonsSeasonIdPut(seasonId: string, userId: string, seasonCreate: SeasonCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeasonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSeasonSeasonsSeasonIdPut(seasonId, userId, seasonCreate, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SeasonsApi.updateSeasonSeasonsSeasonIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * SeasonsApi - factory interface
 * @export
 */
export const SeasonsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SeasonsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Season
         * @param {SeasonBase} seasonBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSeasonSeasonsPost(seasonBase: SeasonBase, options?: any): AxiosPromise<SeasonResponse> {
            return localVarFp.createSeasonSeasonsPost(seasonBase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSeasonSeasonsSeasonIdDelete(seasonId: string, userId: string, options?: any): AxiosPromise<SeasonResponse> {
            return localVarFp.deleteSeasonSeasonsSeasonIdDelete(seasonId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Seasons
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSeasonsSeasonsGet(userId: string, options?: any): AxiosPromise<Array<SeasonResponse>> {
            return localVarFp.getSeasonsSeasonsGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Season
         * @param {string} seasonId 
         * @param {string} userId 
         * @param {SeasonCreate} seasonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSeasonSeasonsSeasonIdPut(seasonId: string, userId: string, seasonCreate: SeasonCreate, options?: any): AxiosPromise<SeasonResponse> {
            return localVarFp.updateSeasonSeasonsSeasonIdPut(seasonId, userId, seasonCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SeasonsApi - object-oriented interface
 * @export
 * @class SeasonsApi
 * @extends {BaseAPI}
 */
export class SeasonsApi extends BaseAPI {
    /**
     * 
     * @summary Create Season
     * @param {SeasonBase} seasonBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeasonsApi
     */
    public createSeasonSeasonsPost(seasonBase: SeasonBase, options?: RawAxiosRequestConfig) {
        return SeasonsApiFp(this.configuration).createSeasonSeasonsPost(seasonBase, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Season
     * @param {string} seasonId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeasonsApi
     */
    public deleteSeasonSeasonsSeasonIdDelete(seasonId: string, userId: string, options?: RawAxiosRequestConfig) {
        return SeasonsApiFp(this.configuration).deleteSeasonSeasonsSeasonIdDelete(seasonId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Seasons
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeasonsApi
     */
    public getSeasonsSeasonsGet(userId: string, options?: RawAxiosRequestConfig) {
        return SeasonsApiFp(this.configuration).getSeasonsSeasonsGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Season
     * @param {string} seasonId 
     * @param {string} userId 
     * @param {SeasonCreate} seasonCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeasonsApi
     */
    public updateSeasonSeasonsSeasonIdPut(seasonId: string, userId: string, seasonCreate: SeasonCreate, options?: RawAxiosRequestConfig) {
        return SeasonsApiFp(this.configuration).updateSeasonSeasonsSeasonIdPut(seasonId, userId, seasonCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TeamsApi - axios parameter creator
 * @export
 */
export const TeamsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Team
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeamTeamsPost: async (teamBase: TeamBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamBase' is not null or undefined
            assertParamExists('createTeamTeamsPost', 'teamBase', teamBase)
            const localVarPath = `/teams/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teamBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Team
         * @param {string} teamId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeamTeamsTeamIdDelete: async (teamId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamId' is not null or undefined
            assertParamExists('deleteTeamTeamsTeamIdDelete', 'teamId', teamId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteTeamTeamsTeamIdDelete', 'userId', userId)
            const localVarPath = `/teams/{team_id}`
                .replace(`{${"team_id"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Teams
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsTeamsGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getTeamsTeamsGet', 'userId', userId)
            const localVarPath = `/teams/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Team
         * @param {string} teamId 
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeamTeamsTeamIdPut: async (teamId: string, teamBase: TeamBase, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamId' is not null or undefined
            assertParamExists('updateTeamTeamsTeamIdPut', 'teamId', teamId)
            // verify required parameter 'teamBase' is not null or undefined
            assertParamExists('updateTeamTeamsTeamIdPut', 'teamBase', teamBase)
            const localVarPath = `/teams/{team_id}`
                .replace(`{${"team_id"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teamBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamsApi - functional programming interface
 * @export
 */
export const TeamsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Team
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTeamTeamsPost(teamBase: TeamBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTeamTeamsPost(teamBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamsApi.createTeamTeamsPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Team
         * @param {string} teamId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTeamTeamsTeamIdDelete(teamId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTeamTeamsTeamIdDelete(teamId, userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamsApi.deleteTeamTeamsTeamIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get Teams
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeamsTeamsGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TeamResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeamsTeamsGet(userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamsApi.getTeamsTeamsGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update Team
         * @param {string} teamId 
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTeamTeamsTeamIdPut(teamId: string, teamBase: TeamBase, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTeamTeamsTeamIdPut(teamId, teamBase, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamsApi.updateTeamTeamsTeamIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * TeamsApi - factory interface
 * @export
 */
export const TeamsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Team
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeamTeamsPost(teamBase: TeamBase, options?: any): AxiosPromise<TeamResponse> {
            return localVarFp.createTeamTeamsPost(teamBase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Team
         * @param {string} teamId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeamTeamsTeamIdDelete(teamId: string, userId: string, options?: any): AxiosPromise<TeamResponse> {
            return localVarFp.deleteTeamTeamsTeamIdDelete(teamId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Teams
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsTeamsGet(userId: string, options?: any): AxiosPromise<Array<TeamResponse>> {
            return localVarFp.getTeamsTeamsGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Team
         * @param {string} teamId 
         * @param {TeamBase} teamBase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeamTeamsTeamIdPut(teamId: string, teamBase: TeamBase, options?: any): AxiosPromise<TeamResponse> {
            return localVarFp.updateTeamTeamsTeamIdPut(teamId, teamBase, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamsApi - object-oriented interface
 * @export
 * @class TeamsApi
 * @extends {BaseAPI}
 */
export class TeamsApi extends BaseAPI {
    /**
     * 
     * @summary Create Team
     * @param {TeamBase} teamBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public createTeamTeamsPost(teamBase: TeamBase, options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).createTeamTeamsPost(teamBase, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Team
     * @param {string} teamId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public deleteTeamTeamsTeamIdDelete(teamId: string, userId: string, options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).deleteTeamTeamsTeamIdDelete(teamId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Teams
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public getTeamsTeamsGet(userId: string, options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).getTeamsTeamsGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Team
     * @param {string} teamId 
     * @param {TeamBase} teamBase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public updateTeamTeamsTeamIdPut(teamId: string, teamBase: TeamBase, options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).updateTeamTeamsTeamIdPut(teamId, teamBase, options).then((request) => request(this.axios, this.basePath));
    }
}



